# Generated by Django 3.2.4 on 2021-06-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('photo', models.URLField(max_length=255, null=True, verbose_name='photo')),
                ('price', models.IntegerField(verbose_name='price')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('pharmacy', models.CharField(max_length=255, verbose_name='pharmacy')),
            ],
            options={
                'verbose_name': 'medicine',
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('photo', models.URLField(max_length=255, null=True, verbose_name='photo')),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('pharmacy', models.CharField(max_length=255, verbose_name='pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPA_app.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'pharmacy',
                'db_table': 'pharmacy',
            },
        ),
    ]
